replicaCount: 1

image:
  repository: image.senses-ai.com/odyssey/livy-cdh6-krb
  pullPolicy: IfNotPresent
  tag: "release-202103021947"

service:
  type: ClusterIP
  port: 9113

env:
  KERBEROS_KEYTAB: "/opt/all.keytab" 
  KERBEROS_PRINCIPAL: "tw"
  TZ: "Asia/Shanghai"

hostAliases:
  - ip: "192.168.10.181"
    hostnames:
    - "cdh6-krb5.senses-ai.com"
    - "cdh6kdc"
  - ip: "192.168.10.218"
    hostnames:
    - "haproxy-kubernetes-apiserver"

resources: 
   limits:
     cpu: 2000m
     memory: 4Gi
   requests:
     cpu: 100m
     memory: 100Mi

keytabPath: "/opt/all.keytab"
keytabFile: "all.keytab"
