version: '2.1'
services:
  bos-plugin:
    image: image.senses-ai.com/odyssey/bos-plugin:release-202103021947
    ports:
      - 18080:8080
    stop_signal: SIGINT
    volumes:
      - ./src/main/resources/application.properties:/app/config/application.properties
      - ./src/main/java/com/ws/SDK/:/tmp/SDK/
    mac_address: 20:04:0f:fa:83:48
    restart: always
