##############################arangodb############################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: "arangodb-pvc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  storageClassName: rook-cephfs
#############################redis############################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "redis-pvc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
##############################activemq############################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "activemq-pvc"
  labels:
    app: activemq
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
#############################mysql############################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "helm-stella-mysql-pvc"
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
