apiVersion: v1
kind: Service
metadata:
  name: airflow-flower
  labels:
    {{- include "airflow-flower.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airflow-flower.selectorLabels" . | nindent 4 }}
