apiVersion: v1
kind: Service
metadata:
  name: eureka-czcb-service
  labels:
    {{- include "eureka-czcb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "eureka-czcb.selectorLabels" . | nindent 4 }}
