replicaCount: 1

image:
  repository: image.senses-ai.com/odyssey/user-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart version.
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  #nodePort: 28080

resources: 
   limits:
     cpu: 500m
     memory: 2Gi
   requests:
     cpu: 100m
     memory: 100Mi

busybox:
   image: busybox
   tag: latest
   imagePullPolicy: IfNotPresent
