apiVersion: v1
kind: Service
metadata:
  #name: redis-headless
  name: redis
  labels:
    {{- include "airflow-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  #clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "airflow-redis.selectorLabels" . | nindent 4 }}
