spring:
  application:
    name: user-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev02.senses-ai.com:3316/stella_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
server:
  port: 28080
  servlet:
    context-path: /auth

jwt:
  secret: javainuse
  header: Authorization
  expiration: 604800
  tokenHead: Bearer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-czcb-service:8080/eureka
czcb:
  datasource:
    url: jdbc:oracle:thin:@192.168.10.91:1521:orcl
    username: root
    password: shanjing0322

unified:
  certification:
    enabled: true
    url:
