replicaCount: 1

image:
  repository: image.senses-ai.com/odyssey/datasource-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart version.
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

env:
  HADOOP_CONF_DIR: "/opt/hadoop/etc/hadoop"
  HADOOP_HOME: "/opt/hadoop"
  KERBEROS_ENABLED: "true"
  KERBEROS_KEYTAB: "/opt/tw.keytab"
  KERBEROS_PRINCIPAL: "tw@CDH6.COM"
  TZ: "Asia/Shanghai"

resources: 
   limits:
     cpu: 1000m
     memory: 4Gi
   requests:
     cpu: 100m
     memory: 100Mi

busybox:
   image: busybox
   tag: latest
   imagePullPolicy: IfNotPresent

hostAliases:
  - ip: "192.168.10.181"
    hostnames:
    - "cdh6-krb5.senses-ai.com"
    - "cdh6kdc"
  - ip: "192.168.10.218"
    hostnames:
    - "haproxy-kubernetes-apiserver"

keytabPath: "/opt/tw.keytab"
keytabFile: "tw.keytab"
