apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-server-czcb.fullname" . }}
  labels:
    {{- include "user-server-czcb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-server-czcb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-server-czcb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 28080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 28080
            initialDelaySeconds: 90
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 28080
            initialDelaySeconds: 90
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: user-server-configmap
            mountPath: /config/
      initContainers:
        - name: init-eureka
          image: "{{ .Values.busybox.image}}:{{ .Values.busybox.tag }}"
          imagePullPolicy: "{{ .Values.busybox.imagePullPolicy }}"
          command: ['sh', '-c', 'until nslookup eureka-czcb-service; do echo waiting for eureka ; sleep 1; done;']
          securityContext:
            privileged: true
      initContainers:
        - name: init-gateway
          image: "{{ .Values.busybox.image}}:{{ .Values.busybox.tag }}"
          imagePullPolicy: "{{ .Values.busybox.imagePullPolicy }}"
          command: ['sh', '-c', 'until nslookup gateway-czcb-service; do echo waiting for gateway; sleep 1; done;']
          securityContext:
            privileged: true
      volumes:
      - name: user-server-configmap
        configMap:
          name: user-server-configmap

