apiVersion: v1
kind: Service
metadata:
  name: "user-server-czcb-service"
  labels:
    {{- include "user-server-czcb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "user-server-czcb.selectorLabels" . | nindent 4 }}
