apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-service
  labels:
    {{- include "airflow-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "airflow-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "airflow-service.selectorLabels" . | nindent 8 }}
    spec:
      hostname: airflow-service
    {{- if .Values.global.hostAliases }}
      hostAliases:
{{ toYaml .Values.global.hostAliases | indent 8 }}
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.global.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolic }}
        env:
        {{- range $key, $value := .Values.global.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: tcp
            containerPort: 5005
            protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
        volumeMounts:
        - name: service-configmap
          mountPath: /config/
        - name: krb5-configmap
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
        - name: hadoop-configmap
          mountPath: /opt/hadoop/etc/hadoop/
        - name: hadoop-yarn-configmap
          mountPath: /opt/hadoop-yarn/etc/hadoop/
        - name: spark-configmap
          mountPath: /opt/spark-2.4.6-bin-hadoop2.7/conf/
        - name: keytab-secret
          mountPath: {{ .Values.global.keytabPath }}
          subPath: {{ .Values.global.keytabFile }}
      volumes:
      - name: service-configmap
        configMap:
          name: airflow-service-configmap
      - name: krb5-configmap
        configMap:
          name: krb5-configmap
      - name: hadoop-configmap
        configMap:
          name: hadoop-configmap
      - name: hadoop-yarn-configmap
        configMap:
          name: hadoop-yarn-configmap
      - name: spark-configmap
        configMap:
          name: spark-configmap
      - name: keytab-secret
        secret:
          secretName: keytab-secret
