apiVersion: v1
kind: Service
metadata:
  name: "user-server"
  labels:
    {{- include "user-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "user-server.selectorLabels" . | nindent 4 }}
