apiVersion: v1
kind: Service
metadata:
  name: "datasource-service"
  labels:
    {{- include "odyssey-datasource.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "odyssey-datasource.selectorLabels" . | nindent 4 }}
