# Default values for arangodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: arangodb/arangodb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "3.7.1"
env:
  ARANGO_ROOT_PASSWORD: "root"
  TZ: "Asia/Shanghai"

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8529

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 128Mi
