apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-worker-krb5-configmap
data:
{{ (.Files.Glob "worker-conf/krb5.conf").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-worker-hadoop-configmap
data:
{{ (.Files.Glob "worker-conf/hadoop/etc/hadoop/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-worker-hadoop-yarn-configmap
data:
{{ (.Files.Glob "worker-conf/hadoop-yarn/etc/hadoop/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-worker-spark-configmap
data:
{{ (.Files.Glob "worker-conf/spark-2.4.6-bin-hadoop2.7/conf/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: airflow-worker-keytab
type: Opaque
data:
{{ (.Files.Glob "worker-conf/*.keytab").AsSecrets| indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-worker-const-configmap
data:
{{ (.Files.Glob "worker-conf/*.py").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-worker-cfg-configmap
data:
{{ (.Files.Glob "worker-conf/*.cfg").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-worker-hive-configmap
data:
{{ (.Files.Glob "worker-conf/apache-hive-2.3.6-bin/conf/*").AsConfig | indent 2 }}
