apiVersion: v1
kind: Service
metadata:
  name: airflow-worker
  labels:
    {{- include "airflow-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webport }}
      targetPort: 8080
      protocol: TCP
      name: af-worker-port
    - port: {{ .Values.service.logport }}
      targetPort: 8793
      protocol: TCP
      name: af-worker-log
  selector:
    {{- include "airflow-worker.selectorLabels" . | nindent 4 }}
