replicaCount: 1

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 6379

env:
  TZ: "Asia/Shanghai"

resources: 
   limits:
     cpu: 1000m
     memory: 4Gi
   requests:
     cpu: 100m
     memory: 100Mi

hostAliases: 
  - ip: "192.168.10.181"
    hostnames:
    - "cdh6-krb5.senses-ai.com"
    - "cdh6kdc"
  - ip: "192.168.10.218"
    hostnames:
    - "haproxy-kubernetes-apiserver"
