apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    {{- include "airflow-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "airflow-gateway.selectorLabels" . | nindent 4 }}
