---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: "cfg-center-data-pvc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs

