apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gateway-czcb"
  labels:
    {{- include "gateway-czcb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gateway-czcb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway-czcb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
           - name: gateway-configmap
             mountPath: /config
      initContainers:
        - name: init-eureka
          image: "{{ .Values.busybox.image}}:{{ .Values.busybox.tag }}"
          imagePullPolicy: "{{ .Values.busybox.imagePullPolicy }}"
          command: ['sh', '-c', 'until nslookup eureka-czcb-service; do echo waiting for eureka ; sleep 1; done;']
          securityContext:
            privileged: true
      volumes:
      - name: gateway-configmap
        configMap:
          name: gateway-czcb-configmap

