apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-web-krb5-configmap
data:
{{ (.Files.Glob "airflow-web-conf/krb5.conf").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-web-hadoop-configmap
data:
{{ (.Files.Glob "airflow-web-conf/hadoop/etc/hadoop/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-web-hadoop-yarn-configmap
data:
{{ (.Files.Glob "airflow-web-conf/hadoop-yarn/etc/hadoop/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-web-spark-configmap
data:
{{ (.Files.Glob "airflow-web-conf/spark-2.4.6-bin-hadoop2.7/conf/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: airflow-web-keytab
type: Opaque
data:
{{ (.Files.Glob "airflow-web-conf/*.keytab").AsSecrets| indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-web-const-configmap
data:
{{ (.Files.Glob "airflow-web-conf/*.py").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-web-cfg-configmap
data:
{{ (.Files.Glob "airflow-web-conf/*.cfg").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: airflow-web-hive-configmap
data:
{{ (.Files.Glob "airflow-web-conf/apache-hive-2.3.6-bin/conf/*").AsConfig | indent 2 }}
