apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  labels:
    {{- include "airflow-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: af-web-port
      nodePort: {{ .Values.service.nodeport }}
  selector:
    {{- include "airflow-web.selectorLabels" . | nindent 4 }}
