replicaCount: 1

image:
  repository: image.senses-ai.com/odyssey/eureka
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

env:
  TZ: "Asia/Shanghai"

resources: 
   limits:
     cpu: 500m
     memory: 2Gi
   requests:
     cpu: 100m
     memory: 100Mi
