apiVersion: v1
kind: Service
metadata:
  name: "arangodb"
  labels:
    app: arangodb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8529
      protocol: TCP
      name: arangodb
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: arangodb
