apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  labels:
    {{- include "airflow-eureka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "airflow-eureka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airflow-eureka.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: eureka-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 80
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 80
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
