apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    {{- include "airflow-eureka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airflow-eureka.selectorLabels" . | nindent 4 }}
